package com.orangehrm;
import java.io.File;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
public class Myinfo_Qualification {
	public static void main(String[] args) throws Throwable {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\acer\\eclipse-workspace\\Orange_Project\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.get("https://opensource-demo.orangehrmlive.com/");
		driver.manage().window().maximize();
		driver.findElement(By.name("txtUsername")).sendKeys("Admin");
		driver.findElement(By.id("txtPassword")).sendKeys("admin123");
		driver.findElement(By.name("Submit")).click();
		driver.findElement(By.id("menu_pim_viewMyDetails")).click();
		driver.findElement(By.xpath("(//a[text()='Qualifications'])[2]")).click();
		driver.findElement(By.xpath("(//input[@type='button'])[18]")).click();
		WebElement language = driver.findElement(By.id("language_code"));
		Select sl = new Select(language);
		sl.selectByIndex(3);
		WebElement fluency = driver.findElement(By.id("language_lang_type"));
		Select sf = new Select(fluency);
		sf.selectByIndex(3);
		WebElement competency = driver.findElement(By.name("language[competency]"));
		Select sc = new Select(competency);
		sc.selectByVisibleText("Good");
		driver.findElement(By.name("language[comments]")).sendKeys("Improve knowledge to read book");
		driver.findElement(By.xpath("(//input[@type='button'])[16]")).click();
		TakesScreenshot ts = (TakesScreenshot)driver;
		File sou = ts.getScreenshotAs(OutputType.FILE);
		File des = new File("C:\\Users\\acer\\eclipse-workspace\\Orange_Project\\Snap\\first.png");
		FileUtils.copyFile(sou, des);
		driver.findElement(By.xpath("(//input[@type='button'])[22]")).click();
		WebElement lictype = driver.findElement(By.id("license_code"));
		Select lt = new Select(lictype);
		lt.selectByIndex(2);
		driver.findElement(By.name("license[license_no]")).sendKeys("1234567890");
		driver.findElement(By.xpath("(//img[@class='ui-datepicker-trigger'])[5]")).click();
		WebElement month = driver.findElement(By.xpath("//select[@data-handler='selectMonth']"));
		Select sm=new Select(month);
		sm.selectByIndex(2);
		WebElement year = driver.findElement(By.xpath("//select[@data-handler='selectYear']"));
		Select sy = new Select(year);
		sy.selectByVisibleText("2002");
		driver.findElement(By.xpath("//a[text()='10']")).click();
		driver.findElement(By.xpath("(//img[@class='ui-datepicker-trigger'])[6]")).click();
		WebElement month1 = driver.findElement(By.xpath("//select[@data-handler='selectMonth']"));
		Select ms = new Select(month1);
		ms.selectByIndex(2);
		WebElement year1 = driver.findElement(By.xpath("//select[@data-handler='selectYear']"));
		Select ys = new Select(year1);
		ys.selectByVisibleText("2022");
		driver.findElement(By.xpath("//a[text()='9']")).click();
		driver.findElement(By.xpath("(//input[@value='Save'])[5]")).click();
		TakesScreenshot tks = (TakesScreenshot)driver;
		File sour = ts.getScreenshotAs(OutputType.FILE);
		File dest = new File("C:\\Users\\acer\\eclipse-workspace\\Orange_Project\\Snap\\second.png");
		FileUtils.copyFile(sour, dest);
	}
}
